In [1]:
import numpy as np

# Python classes
<font color = magenta>Jessica Reyes<font> <br>
<font color = black>We have seen that Python operators such as multiplication behave differently on NumPy and pandas arrays / DataFrames than on Python lists:<font>

In [2]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [3]:
np.array([1,2,3]) * 3

array([3, 6, 9])

The designers of NumPy and pandas have redefined the various mathematical operators to function in a way that is more relevant for their intended uses.  This is called **operator overloading**.  In this notebook we will see how this is coded, and also learn other special features of Python classes.
To demonstrate that, we will implement a class that represents a two dimensional array, i.e. a matrix.


In [4]:
class matrix:
    def __init__(self, _matrix):
        self._matrix = np.array(_matrix)

    def __str__(self) :
        print('in __str__')
        return str(self._matrix)

    def __repr__(self) :
        print('in __repr__')
        return 'matrix' + repr(self._matrix)[5:]
        
    def __len__(self):
        """
        return the number of rows in the matrix
        """
        return len(self._matrix)

    def __getitem__(self, item):
        """
        The result of applying the square brackets operator
        """
        return self._matrix[item]

    def __eq__(self, other):
        """
        define matrix equality
        """
        if not(isinstance(other, matrix)):
            raise ValueError('wrong type of argument to __eq__')
        return np.all(self._matrix == other._matrix)
    
    def __mul__(self, other):
        """
        multiplication by a matrix or a scalar 
        """
        if isinstance(other, matrix):
            # matrix multiplication (elementwise multiplication)
            return matrix(self._matrix * other._matrix)
        else :
            # assume "other" is a number
            other = float(other)
            return matrix(self._matrix * other)

    def __add__(self, other) :
        """
        define the addition operator
        """
        if isinstance(other, matrix):
            # matrix multiplication (elementwise multiplication)
            return matrix(self._matrix + other._matrix)
        else :
            # assume "other" is a number
            other = float(other)
            return matrix(self._matrix + other)        
    
    def transpose(self):
        return self._matrix.transpose()


Let's try to understand the code a bit better, especially all those methods with funky underscore names.  Those have special roles when implementing Python classes.

First is the constructor which is named `__init__` in Python.  It is called whenever you create a new object of the class:

In [5]:
m = matrix([[1,2,3],[4,5,6]])

Both `__str__` and `__repr__` are methods that return a string representation of a Python object.  But they are called in different situations:

In [6]:
m

in __repr__


matrix([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(m)

in __str__
[[1 2 3]
 [4 5 6]]


`__str__` is analogous to Java's `toString` method, and its role is to provide a readable output for the user.  `__repr__` is usually implemented so that 
```Python
eval(repr(object)) == object
```
I.e. it is a representation of the object whose objective is to *reproduce* it.  We can easily verify that:

In [8]:
repr(m)

in __repr__


'matrix([[1, 2, 3],\n       [4, 5, 6]])'

In [9]:
eval(repr(m))

in __repr__
in __repr__


matrix([[1, 2, 3],
       [4, 5, 6]])

In [10]:
eval(repr(m)) == m

in __repr__


True

The bracket operator works as expected:

In [11]:
m[0]

array([1, 2, 3])

In [12]:
m[0,0]

1

As does the multiplication operator:

In [13]:
m*3

in __repr__


matrix([[ 3.,  6.,  9.],
       [12., 15., 18.]])

and the addition operator:

In [14]:
m + m

in __repr__


matrix([[ 2,  4,  6],
       [ 8, 10, 12]])

## Exercise

Implement a class called **vector** that represents the concept of a one dimensional array of numbers.  Use a Python list for storing the array.
Your class should have the following methods:

* A constructor that creates a new object of the class out of a Python list or NumPy array.  It then stores the data in a Python list.  It converts each element into a floating point number.  
* Appropriate `__str__` and `__repr__` methods
* An `__eq__` method that verifies object equality.  We will define two vectors as equal iff all their elements are equal.
* Functions that implement the multiplication and addition operators.  Multiplication should be able to handle scalar multiplication, and addition should handle addition of two vectors or a vector and scalar.
* Implement the bracket operator in an appropriate way.


In [15]:
class Vector:
    def __init__(self, data):
        # convert array to a list of floats
        if isinstance(data, np.ndarray):
            self.data = [float(x) for x in data]
        else:
            self.data = [float(x) for x in data]
    
    def __str__(self):
        # Return a string representation of the vector 
        return f"Vector({self.data})"
    
    def __repr__(self):
        return f"Vector({self.data!r})"
    
    def __eq__(self, other):
        # Check for equality between two vectors
        if isinstance(other, Vector):
            return self.data == other.data
        return False
    
    def __add__(self, other):
        if isinstance(other, Vector):
            # Vector addition
            if len(self.data) != len(other.data):
                raise ValueError("Vectors must have the same length to add them.")
            return Vector([x + y for x, y in zip(self.data, other.data)])
        elif isinstance(other, (int, float)):
            # Vector + scalar
            return Vector([x + other for x in self.data])
        else:
            raise TypeError("Unsupported addition type.")
    
    def __mul__(self, other):
        if isinstance(other, (int, float)):
            # Scalar multiplication
            return Vector([x * other for x in self.data])
        elif isinstance(other, Vector):
            # Vector multiplication
            if len(self.data) != len(other.data):
                raise ValueError("Vectors must have the same length to multiply them element-wise.")
            return Vector([x * y for x, y in zip(self.data, other.data)])
        else:
            raise TypeError("Unsupported multiplication type.")
    
    def __getitem__(self, index):
        # Bracket operator 'get'
        return self.data[index]
    
    def __setitem__(self, index, value):
        # Bracket operator 'set'
        self.data[index] = value
        
v1 = Vector([1, 2, 3])
v2 = Vector([4, 5, 6])

# Printing vector
print(v1) 

# Checking equality
print(v1 == v2)  # Output: False

# Adding two vectors
v3 = v1 + v2
print(v3)  

# Scalar multiplication
v4 = v1 * 2
print(v4) 

# Accessing elements with the bracket operator
print(v1[1])  

# Modifying elements with the bracket operator
v1[1] = 10
print(v1) 

Vector([1.0, 2.0, 3.0])
False
Vector([5.0, 7.0, 9.0])
Vector([2.0, 4.0, 6.0])
2.0
Vector([1.0, 10, 3.0])
